name: Deploy Agent - TEST

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/deploy-agent-reusable.yml

    with:
      environment: test
      agent_name: ai-agent-platform
      terraform_plan: true
      deploy_powerplatform: true
